HW5 is completed
sterligov/otus_homework pull request #5
Opened 2020-09-22 10:50 UTC by sterligov

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-22 16:20 UTC, kulti requested changes
Решена немного не та задача. В дискашене написал, что именно подразумевалось в этом ДЗ. Формулировку ДЗ поправили.

2020-09-22 16:20 UTC, kulti commented on hw05_parallel_execution/run.go
> +		go func(task Task) {
Получается, что количество созданных горутин будет равно количеству тасок, а не maxGoroutine. Количество одновременных горутин, конечно, не превысит maxGoroutine из-за канала sem, но смысл задания в том, чтобы создавалось только maxGoroutine горутин, которые выполняют таски.

Раньше задание можно было понять двояко. Теперь формулировка дополнена:
> количество создаваемых горутин не должно зависеть от числа заданий, т.е. функция должна запусать N горутин для параллельно обработки заданий и, возможно, еще несколько вспомогательных горутин;

2020-09-22 16:20 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Nil(t, result)
Рекомендую:
1. Не называть ошибку result, чтобы не сбивать с толку читающего код.
2. Использовать проверку NoError

Вот так:
```
err := Run(tasks, workersCount, maxErrorsCount)
require.NoError(t, err)
```

или даже так:
```
require.NoError(t, Run(tasks, workersCount, maxErrorsCount))
```

намного проще понять, что происходит.

2020-09-26 07:39 UTC, kulti requested changes

2020-09-26 07:39 UTC, kulti commented on hw05_parallel_execution/run.go
> +			taskCh <- task
Если все воркеры выйдут, то ни одна горутина не будет читать из taskCh. В итоге runTasks зависнет навсегда.

Это может произойти так:
1. В этой горутине select выбирает ветку default, т.к. канал done еще открыт.
2. Канал done закрывается.
3. В горутинах-воркерах select выбиарет ветку done, и воркеры завершают работу.
4. Эта горутина навсегда зависает на записи в канал.

Раз вы идете вперед программы, то рекомендую повнимательнее почитать про select. Думаю, решение быстро найдется.

2020-09-28 10:41 UTC, kulti approved these changes
Теперь все в порядке. ДЗ принято — 10/10.

2020-09-28 10:41 UTC, kulti commented on hw05_parallel_execution/run.go
> +	}
Довольно неэфективный цикл получился.

1. В канал пишутся не только ошибки, но и nil. Происходит бесполезное переключение горутин.
2. Цикл продолжает крутиться, даже если лимит ошибок превышен.

Для учебного ДЗ не страшно. В будущих задачах начнет получаться еще лучше, чем сейчас.

2020-09-28 10:43 UTC, sterligov commented on hw05_parallel_execution/run.go
> +	}
Понял. Спасибо за замечание.

2020-09-28 10:44 UTC, merged